sudo: required

language: c#

services:
  - docker

env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Integration

before_install:
  - sh prepare.sh
  - export EnableNuGetPackageRestore=true

script:
  - sh init.sh
  - sh build.sh
  - sh test.sh $TEST_SUITE
